CREATE DATABASE Pharmacity
GO

USE Pharmacity
GO

/***** CREATE TABLE *****/
/* Create Table Vitri */
CREATE TABLE ViTri(
	ID VARCHAR(10) NOT NULL, 
	TEN NVARCHAR(100) NOT NULL
);
ALTER TABLE Vitri ADD CONSTRAINT PK_Vitri PRIMARY KEY(ID) 

/* Create Table Nhanvien */
CREATE TABLE Nhanvien(
	IDNV VARCHAR(10) NOT NULL, 
	HOTEN NVARCHAR(100) NOT NULL,
	GIOITINH NVARCHAR(7) NOT NULL,
	DOB DATETIME NOT NULL,
	QUEQUAN NVARCHAR(50) NOT NULL,
	SDT VARCHAR(12) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	IDVitri VARCHAR(10) NOT NULL
);
ALTER TABLE Nhanvien ADD CONSTRAINT PK_NV PRIMARY KEY(IDNV) 
ALTER TABLE Nhanvien ADD CONSTRAINT FK_NV FOREIGN KEY(IDVitri) REFERENCES Vitri(ID) 

/* Create Table Taikhoan */
CREATE TABLE Taikhoan(
	ID VARCHAR(100) NOT NULL, 
	TENDANGNHAP VARCHAR(10) NOT NULL,
	MATKHAU VARCHAR(50) NOT NULL,
	QUYEN INT NOT NULL
);
ALTER TABLE Taikhoan ADD CONSTRAINT PK_TK PRIMARY KEY(ID) 
ALTER TABLE Taikhoan ALTER COLUMN TENDANGNHAP VARCHAR(50) NOT NULL

/* Create Table Khachhang */
CREATE TABLE Khachhang(
	IDKH VARCHAR(10) NOT NULL, 
	HOTEN NVARCHAR(100) NOT NULL,
	GIOITINH NVARCHAR(7) NOT NULL,
	DOB DATETIME NOT NULL,
	QUEQUAN NVARCHAR(50) NOT NULL,
	SDT VARCHAR(12) NOT NULL,
);
ALTER TABLE Khachhang ADD CONSTRAINT PK_KH PRIMARY KEY(IDKH) 


/***** CREATE FUNCTION & PROCEDURE *****/
/***** Vi tri *****/
CREATE PROCEDURE INSERT_VT
(@ID VARCHAR(10), @TEN NVARCHAR(100))
AS
BEGIN
	INSERT INTO Vitri VALUES (@ID, @TEN)
END
GO

CREATE PROCEDURE UPDATE_VT
(@ID VARCHAR(10), @TEN NVARCHAR(100))
AS
BEGIN
	UPDATE Vitri SET TEN = @TEN WHERE ID = @ID 
END
GO

/***** Nhan vien *****/
/* Lay ra so dem ID */
CREATE FUNCTION LAST_ID()
RETURNS INT
AS
BEGIN
	DECLARE @COUNT INT
	SELECT @COUNT =  (SELECT COUNT(IDNV) FROM Nhanvien WHERE IDNV LIKE '%NV%')
	RETURN @COUNT
END

/* Lay ra ID */
CREATE FUNCTION GET_ID()
RETURNS VARCHAR(10)
AS
BEGIN
	DECLARE @ID VARCHAR(10)
	RETURN  (SELECT TOP 1 IDNV FROM Nhanvien WHERE IDNV LIKE '%NV%' ORDER BY IDNV DESC)
END

/* Tu dong tang ID */
CREATE FUNCTION AUTO_IDNV()
RETURNS VARCHAR(10)
AS
BEGIN
	DECLARE @ID VARCHAR(10)
	DECLARE @NID VARCHAR(10)
	SET @ID = dbo.GET_ID()
	DECLARE @COUNT INT 
	SET @COUNT = dbo.LAST_ID()
	IF (@COUNT) = 0
		SET @NID = 'NV000'
	ELSE 
		SET @NID = CASE 
			WHEN @COUNT > 0 AND @COUNT < 9 THEN 'NV00' + CONVERT(CHAR, (CAST(SUBSTRING(@ID, LEN(@ID), 3) AS INT) + 1 ))
			WHEN @COUNT >= 9 THEN 'NV0' + CONVERT(CHAR, (CAST(SUBSTRING(@ID, LEN(@ID), 3) AS INT) + 1 ))
		END
	RETURN @NID		
END

/* Insert NV */
CREATE PROCEDURE INSERT_NV
(@HOTEN NVARCHAR(100), @GIOITINH NVARCHAR(7), @DOB DATETIME, 
 @QUEQUAN NVARCHAR(50), @SDT VARCHAR(12), @EMAIL VARCHAR(50), @IDVitri VARCHAR(10))
AS
BEGIN
	DECLARE @IDNV VARCHAR(10)
	SET @IDNV = dbo.AUTO_IDNV()
	INSERT INTO Nhanvien VALUES (@IDNV, @HOTEN , @GIOITINH , @DOB , 
								 @QUEQUAN, @SDT , @EMAIL , @IDVitri)
END
GO

/* Insert TK */
CREATE PROCEDURE INSERT_TK
(@TENDANGNHAP VARCHAR(50) , @MATKHAU VARCHAR(50), @QUYEN INT)
AS
BEGIN
DECLARE @ID VARCHAR(10)
	SET @ID = dbo.GET_ID()
	INSERT INTO Taikhoan VALUES (@ID, @TENDANGNHAP , @MATKHAU , @QUYEN)
END

/* Update NV */ 
CREATE PROCEDURE UPDATE_NV
(@IDNV VARCHAR(10), @HOTEN NVARCHAR(100), @GIOITINH NVARCHAR(7), @DOB DATETIME, 
 @QUEQUAN NVARCHAR(50), @SDT VARCHAR(12), @EMAIL VARCHAR(50), @IDVitri VARCHAR(10))
AS
BEGIN
	UPDATE Nhanvien SET 
	HOTEN = @HOTEN,
	GIOITINH = @GIOITINH, 
	DOB = @DOB, 
	QUEQUAN = @QUEQUAN,
	SDT = @SDT, 
	EMAIL = @EMAIL, 
	IDVitri = @IDVitri
	WHERE IDNV = @IDNV
END
GO

/* Update TKNV */
CREATE PROCEDURE UPDATE_TKNV
(@ID VARCHAR(10), @TENDANGNHAP VARCHAR(100) , @MATKHAU VARCHAR(50), @QUYEN INT)
AS
BEGIN
	UPDATE Taikhoan SET 
	TENDANGNHAP = @TENDANGNHAP,
	MATKHAU = @MATKHAU, 
	QUYEN = @QUYEN
	WHERE ID = @ID 
END


/***** INSERT *****/
/* Insert Vi tri */ 
INSERT INTO Vitri VALUES
('AD', N'Quản lý'), 
('BH', N'Nhân viên bán hàng'), 
('KHO', N'Nhân viên kho'), 
('TN', N'Nhân viên thu ngân')
/* Insert NV*/ 
INSERT INTO Nhanvien VALUES ('ADMIN', N'Phạm Huỳnh Anh Thư', N'Nữ', '07/03/2002', N'Đồng Tháp', '0946020824', 'phamthushame2002@gmail.com', 'AD')
/* Insert Account*/ 
INSERT INTO Taikhoan VALUES ('ADMIN', 'admin', '12345678', 2)


/* Select 
SELECT *FROM Vitri
SELECT *FROM Nhanvien
SELECT *FROM Taikhoan
SELECT *FROM Khachhang
*/

/* DELETE FROM Customer WHERE ID = 'KH000' */
/* Drop
DROP FUNCTION [dbo].[LAST_ID]
DROP FUNCTION [dbo].[GET_ID]
DROP FUNCTION [dbo].[AUTO_IDNV] 
DROP PROCEDURE [dbo].[INSERT_NV]
DROP PROCEDURE [dbo].[INSERT_ACCOUNT]
DROP PROCEDURE [dbo].[UPDATE_NV]
DROP PROCEDURE [dbo].[UPATE_ACCOUNT]

DROP FUNCTION [dbo].[LAST_IDKH]
DROP FUNCTION [dbo].[AUTO_IDKH] 
DROP PROCEDURE [dbo].[INSERT_KH]
DROP PROCEDURE [dbo].[INSERT_ACCOUNTKH]
*/

/* 
DELETE FROM Employee WHERE ID_EMPLOYEE LIKE '%NV%'
DELETE FROM Account WHERE ID LIKE '%NV%'
*/